language: go
sudo: required

go:
  - 1.11.x
  - stable
  - master

matrix:
  # Failing on the development version of Go isn't too bad.
  allow_failures:
    - go: master

env:
  - GO111MODULE=on

# Override Travis's default 'go get' step, since we use Go modules
install:
  - go mod download

before_script:
  # Don't record coverage for protobuf/gen & replay/nondefault
  - cover_packages=$(go list ./... | grep -v "protobuf/gen\|replay/nondefault" | awk -vORS=',' '{ print $1 }' | sed 's/,$/\n/')

script:
  - go test -coverprofile=coverage.txt -covermode=count -coverpkg=$cover_packages ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.11

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0a4814dca40d4a21a37
    on_success: change
    on_failure: always
